# https://maku.blog/p/j6iu7it/
# https://qiita.com/mysticatea/items/9da94240f29ea516ae87
root: true
env:
  es12: true
  browser: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  project: ./tsconfig.json
  sourceType: module
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
plugins:
  - svelte3
  - "@typescript-eslint"
overrides:
  - files:
      - "*.svelte"
    processor: svelte3/svelte3
settings:
  svelte3/typescript: true
rules:
  semi:
    - error
    - always
  semi-spacing:
    - error
    - after: true
      before: false
  semi-style:
    - error
    - last
  no-unexpected-multiline: error
  no-unreachable: error
  no-extra-semi: error
  quotes:
    - error
    - double
    - avoidEscape: true
